# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config  -id {Vivado 12-1790}  -string {{Evaluation} {features} {should} {NOT} {be} {used} {in} {production} {systems.}}  -new_severity {WARNING} 
set_msg_config  -id {BD 41-1343}  -new_severity {WARNING} 
set_msg_config  -id {BD 41-1306}  -new_severity {WARNING} 
set_msg_config  -id {BD 41-1276}  -severity {CRITICAL WARNING}  -new_severity {ERROR} 
set_msg_config  -id {IP_Flow 19-3656}  -new_severity {INFO} 
set_msg_config  -id {IP_Flow 19-4623}  -new_severity {INFO} 
set_msg_config  -id {IP_Flow 19-459}  -new_severity {INFO} 
set_msg_config  -id {Place 30-73}  -string {{axi_spi}}  -new_severity {WARNING} 
set_msg_config  -string {{PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY}}  -new_severity {WARNING} 
create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/adi/hdl/projects/daq2/zc706/daq2_zc706.cache/wt [current_project]
set_property parent.project_path C:/adi/hdl/projects/daq2/zc706/daq2_zc706.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zc706:part0:1.2 [current_project]
set_property ip_repo_paths {
  {c:/Users/Xandr/OneDrive - Universidade de Aveiro/adi/hdl/projects/daq2/ip_repo/Measurements_1.0}
  {c:/Users/Xandr/OneDrive - Universidade de Aveiro/VivadoProjects/xfer_req_signal_projection/xfer_req_signal_projection.srcs/sources_1/new}
  {c:/Users/Xandr/OneDrive - Universidade de Aveiro/VivadoProjects/TDC_vhdl/TDC_vhdl.srcs/sources_1/new}
  {c:/Users/Xandr/OneDrive - Universidade de Aveiro/adi/hdl/projects/daq2/ip_repo/UserMemoryAccess_1.0}
  {c:/Users/Xandr/OneDrive - Universidade de Aveiro/adi/hdl/projects/daq2/ip_repo/Singleshot_1.0}
  {c:/Users/Xandr/OneDrive - Universidade de Aveiro/adi/hdl/projects/daq2/ip_repo/USER_PIN_CONTROL_1.0}
  {c:/Users/Xandr/OneDrive - Universidade de Aveiro/MEMORY_Buffer/MEMORY_Buffer.srcs/sources_1/new}
  c:/adi/hdl/library
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/adi/hdl/projects/daq2/zc706/daq2_zc706.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/adi/hdl/library/xilinx/common/ad_iobuf.v
  C:/adi/hdl/projects/daq2/common/daq2_spi.v
  C:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/imports/hdl/system_wrapper.v
  C:/adi/hdl/projects/daq2/zc706/system_top.v
}
read_vhdl -library xil_defaultlib {
  C:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/new/StateMachine.vhd
  C:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/new/Counter_Xbits.vhd
  C:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/new/FlipflopD.vhd
}
add_files C:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_axi_ad9144_fifo_0/util_dacfifo_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_tx_axi_0/axi_jesd204_tx_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_tx_0/system_tx_0_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/xilinx/common/up_xfer_status_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/xilinx/common/ad_rst_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/xilinx/common/up_xfer_cntrl_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_axi_ad9144_dma_0/system_axi_ad9144_dma_0_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_rx_axi_0/axi_jesd204_rx_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_rx_0/system_rx_0_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/xilinx/common/up_clock_mon_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/xilinx/common/up_xfer_status_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/xilinx/common/ad_rst_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/xilinx/common/up_xfer_cntrl_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_util_daq2_xcvr_0/util_adxcvr_constr.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_axi_ad9144_jesd_rstgen_0/system_axi_ad9144_jesd_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_axi_ad9144_jesd_rstgen_0/system_axi_ad9144_jesd_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_axi_ad9680_jesd_rstgen_0/system_axi_ad9680_jesd_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_axi_ad9680_jesd_rstgen_0/system_axi_ad9680_jesd_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_blk_mem_gen_0_0_1/system_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_1/system_axi_bram_ctrl_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_pc_8/system_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_pc_2_1/system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_pc_3/system_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_pc_4/system_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_pc_5/system_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_pc_6/system_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_pc_7/system_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_pc_9/system_auto_pc_9_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_ds_0/system_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_ds_0/system_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_auto_ds_0/system_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/constrs_1/new/debug.xdc
set_property used_in_implementation false [get_files C:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/constrs_1/new/debug.xdc]

read_xdc C:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files C:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/constrs_1/new/system.xdc]

read_xdc C:/adi/hdl/projects/daq2/zc706/system_constr.xdc
set_property used_in_implementation false [get_files C:/adi/hdl/projects/daq2/zc706/system_constr.xdc]

read_xdc C:/adi/hdl/projects/common/zc706/zc706_plddr3_constr.xdc
set_property used_in_implementation false [get_files C:/adi/hdl/projects/common/zc706/zc706_plddr3_constr.xdc]

read_xdc C:/adi/hdl/projects/common/zc706/zc706_system_constr.xdc
set_property used_in_implementation false [get_files C:/adi/hdl/projects/common/zc706/zc706_system_constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system_top -part xc7z045ffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
