set_property SRC_FILE_INFO {cfile:c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc rfile:../../../daq2_zc706.srcs/sources_1/bd/system/ip/system_sys_ps7_0/system_sys_ps7_0.xdc id:1 order:EARLY scoped_inst:i_system_wrapper/system_i/sys_ps7/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/constrs_1/new/debug.xdc rfile:../../../daq2_zc706.srcs/constrs_1/new/debug.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:C:/adi/hdl/projects/daq2/zc706/system_constr.xdc rfile:../../../system_constr.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:C:/adi/hdl/projects/common/zc706/zc706_plddr3_constr.xdc rfile:../../../../../common/zc706/zc706_plddr3_constr.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:C:/adi/hdl/projects/common/zc706/zc706_system_constr.xdc rfile:../../../../../common/zc706/zc706_system_constr.xdc id:5} [current_design]
set_property SRC_FILE_INFO {cfile:c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_tx_axi_0/axi_jesd204_tx_constr.xdc rfile:../../../daq2_zc706.srcs/sources_1/bd/system/ip/system_tx_axi_0/axi_jesd204_tx_constr.xdc id:6 order:LATE scoped_inst:i_system_wrapper/system_i/axi_ad9144_jesd/tx_axi/inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/adi/hdl/projects/daq2/zc706/daq2_zc706.srcs/sources_1/bd/system/ip/system_rx_axi_0/axi_jesd204_rx_constr.xdc rfile:../../../daq2_zc706.srcs/sources_1/bd/system/ip/system_rx_axi_0/axi_jesd204_rx_constr.xdc id:7 order:LATE scoped_inst:i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst} [current_design]
current_instance i_system_wrapper/system_i/sys_ps7/inst
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C18" [get_ports "MIO[53]"]
set_property src_info {type:SCOPED_XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D19" [get_ports "MIO[52]"]
set_property src_info {type:SCOPED_XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F19" [get_ports "MIO[51]"]
set_property src_info {type:SCOPED_XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A19" [get_ports "MIO[50]"]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D18" [get_ports "MIO[49]"]
set_property src_info {type:SCOPED_XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C19" [get_ports "MIO[48]"]
set_property src_info {type:SCOPED_XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A18" [get_ports "MIO[47]"]
set_property src_info {type:SCOPED_XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F20" [get_ports "MIO[46]"]
set_property src_info {type:SCOPED_XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H18" [get_ports "MIO[45]"]
set_property src_info {type:SCOPED_XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E20" [get_ports "MIO[44]"]
set_property src_info {type:SCOPED_XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E18" [get_ports "MIO[43]"]
set_property src_info {type:SCOPED_XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D20" [get_ports "MIO[42]"]
set_property src_info {type:SCOPED_XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J18" [get_ports "MIO[41]"]
set_property src_info {type:SCOPED_XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B20" [get_ports "MIO[40]"]
set_property src_info {type:SCOPED_XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F18" [get_ports "MIO[39]"]
set_property src_info {type:SCOPED_XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A20" [get_ports "MIO[38]"]
set_property src_info {type:SCOPED_XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B21" [get_ports "MIO[37]"]
set_property src_info {type:SCOPED_XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H17" [get_ports "MIO[36]"]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G21" [get_ports "MIO[35]"]
set_property src_info {type:SCOPED_XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K18" [get_ports "MIO[34]"]
set_property src_info {type:SCOPED_XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G22" [get_ports "MIO[33]"]
set_property src_info {type:SCOPED_XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K17" [get_ports "MIO[32]"]
set_property src_info {type:SCOPED_XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H21" [get_ports "MIO[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L18" [get_ports "MIO[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H22" [get_ports "MIO[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L17" [get_ports "MIO[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G20" [get_ports "MIO[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M17" [get_ports "MIO[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G19" [get_ports "MIO[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M19" [get_ports "MIO[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J21" [get_ports "MIO[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L20" [get_ports "MIO[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J19" [get_ports "MIO[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M20" [get_ports "MIO[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J20" [get_ports "MIO[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K20" [get_ports "MIO[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K21" [get_ports "MIO[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L19" [get_ports "MIO[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C22" [get_ports "MIO[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B22" [get_ports "MIO[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F22" [get_ports "MIO[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E21" [get_ports "MIO[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A23" [get_ports "MIO[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E22" [get_ports "MIO[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A24" [get_ports "MIO[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C21" [get_ports "MIO[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B24" [get_ports "MIO[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D24" [get_ports "MIO[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C24" [get_ports "MIO[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E23" [get_ports "MIO[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C23" [get_ports "MIO[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F23" [get_ports "MIO[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D23" [get_ports "MIO[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F24" [get_ports "MIO[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M21" [get_ports "DDR_VRP"]
set_property src_info {type:SCOPED_XDC file:1 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N21" [get_ports "DDR_VRN"]
set_property src_info {type:SCOPED_XDC file:1 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N23" [get_ports "DDR_WEB"]
set_property src_info {type:SCOPED_XDC file:1 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N24" [get_ports "DDR_RAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L23" [get_ports "DDR_ODT"]
set_property src_info {type:SCOPED_XDC file:1 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F25" [get_ports "DDR_DRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L28" [get_ports "DDR_DQS[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G29" [get_ports "DDR_DQS[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C29" [get_ports "DDR_DQS[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C26" [get_ports "DDR_DQS[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L29" [get_ports "DDR_DQS_n[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F29" [get_ports "DDR_DQS_n[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B29" [get_ports "DDR_DQS_n[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B26" [get_ports "DDR_DQS_n[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A27" [get_ports "DDR_DQ[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A29" [get_ports "DDR_DQ[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E27" [get_ports "DDR_DQ[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D26" [get_ports "DDR_DQ[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E26" [get_ports "DDR_DQ[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B25" [get_ports "DDR_DQ[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D25" [get_ports "DDR_DQ[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M30" [get_ports "DDR_DQ[31]"]
set_property src_info {type:SCOPED_XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L30" [get_ports "DDR_DQ[30]"]
set_property src_info {type:SCOPED_XDC file:1 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B27" [get_ports "DDR_DQ[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M29" [get_ports "DDR_DQ[29]"]
set_property src_info {type:SCOPED_XDC file:1 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K30" [get_ports "DDR_DQ[28]"]
set_property src_info {type:SCOPED_XDC file:1 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J28" [get_ports "DDR_DQ[27]"]
set_property src_info {type:SCOPED_XDC file:1 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J30" [get_ports "DDR_DQ[26]"]
set_property src_info {type:SCOPED_XDC file:1 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K27" [get_ports "DDR_DQ[25]"]
set_property src_info {type:SCOPED_XDC file:1 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J29" [get_ports "DDR_DQ[24]"]
set_property src_info {type:SCOPED_XDC file:1 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F30" [get_ports "DDR_DQ[23]"]
set_property src_info {type:SCOPED_XDC file:1 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G30" [get_ports "DDR_DQ[22]"]
set_property src_info {type:SCOPED_XDC file:1 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F28" [get_ports "DDR_DQ[21]"]
set_property src_info {type:SCOPED_XDC file:1 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E30" [get_ports "DDR_DQ[20]"]
set_property src_info {type:SCOPED_XDC file:1 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E25" [get_ports "DDR_DQ[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "E28" [get_ports "DDR_DQ[19]"]
set_property src_info {type:SCOPED_XDC file:1 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H28" [get_ports "DDR_DQ[18]"]
set_property src_info {type:SCOPED_XDC file:1 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G27" [get_ports "DDR_DQ[17]"]
set_property src_info {type:SCOPED_XDC file:1 line:507 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H27" [get_ports "DDR_DQ[16]"]
set_property src_info {type:SCOPED_XDC file:1 line:511 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D29" [get_ports "DDR_DQ[15]"]
set_property src_info {type:SCOPED_XDC file:1 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D28" [get_ports "DDR_DQ[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D30" [get_ports "DDR_DQ[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C28" [get_ports "DDR_DQ[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A28" [get_ports "DDR_DQ[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A30" [get_ports "DDR_DQ[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A25" [get_ports "DDR_DQ[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K28" [get_ports "DDR_DM[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H29" [get_ports "DDR_DM[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B30" [get_ports "DDR_DM[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:551 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "C27" [get_ports "DDR_DM[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:555 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "N22" [get_ports "DDR_CS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:559 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M22" [get_ports "DDR_CKE"]
set_property src_info {type:SCOPED_XDC file:1 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K25" [get_ports "DDR_Clk"]
set_property src_info {type:SCOPED_XDC file:1 line:567 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J25" [get_ports "DDR_Clk_n"]
set_property src_info {type:SCOPED_XDC file:1 line:571 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M24" [get_ports "DDR_CAS_n"]
set_property src_info {type:SCOPED_XDC file:1 line:575 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M25" [get_ports "DDR_BankAddr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:579 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M26" [get_ports "DDR_BankAddr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:583 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "M27" [get_ports "DDR_BankAddr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:587 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J23" [get_ports "DDR_Addr[9]"]
set_property src_info {type:SCOPED_XDC file:1 line:591 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "F27" [get_ports "DDR_Addr[8]"]
set_property src_info {type:SCOPED_XDC file:1 line:595 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K22" [get_ports "DDR_Addr[7]"]
set_property src_info {type:SCOPED_XDC file:1 line:599 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H26" [get_ports "DDR_Addr[6]"]
set_property src_info {type:SCOPED_XDC file:1 line:603 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G24" [get_ports "DDR_Addr[5]"]
set_property src_info {type:SCOPED_XDC file:1 line:607 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J26" [get_ports "DDR_Addr[4]"]
set_property src_info {type:SCOPED_XDC file:1 line:611 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G25" [get_ports "DDR_Addr[3]"]
set_property src_info {type:SCOPED_XDC file:1 line:615 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L27" [get_ports "DDR_Addr[2]"]
set_property src_info {type:SCOPED_XDC file:1 line:619 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K26" [get_ports "DDR_Addr[1]"]
set_property src_info {type:SCOPED_XDC file:1 line:623 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "J24" [get_ports "DDR_Addr[14]"]
set_property src_info {type:SCOPED_XDC file:1 line:627 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H23" [get_ports "DDR_Addr[13]"]
set_property src_info {type:SCOPED_XDC file:1 line:631 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "K23" [get_ports "DDR_Addr[12]"]
set_property src_info {type:SCOPED_XDC file:1 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "H24" [get_ports "DDR_Addr[11]"]
set_property src_info {type:SCOPED_XDC file:1 line:639 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "G26" [get_ports "DDR_Addr[10]"]
set_property src_info {type:SCOPED_XDC file:1 line:643 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "L25" [get_ports "DDR_Addr[0]"]
set_property src_info {type:SCOPED_XDC file:1 line:647 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "D21" [get_ports "PS_PORB"]
set_property src_info {type:SCOPED_XDC file:1 line:650 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "B19" [get_ports "PS_SRSTB"]
set_property src_info {type:SCOPED_XDC file:1 line:653 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN "A22" [get_ports "PS_CLK"]
current_instance
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list u_ila_0_clk_out1]]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list i_system_wrapper/system_i/clk_wiz_0/inst/clk_out1]]
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list i_system_wrapper/system_i/clk_wiz_0_clk_out1]]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list i_system_wrapper/system_i/edgeDetector_0_redge_o]]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list i_system_wrapper/system_i/Singleshot_0_single_shot]]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list i_system_wrapper/system_i/Start_1CLK_STOP_0_start_o]]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list i_system_wrapper/system_i/Start_1CLK_STOP_0_stop_o]]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list i_system_wrapper/system_i/tdc_0_wr_en_o]]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
set_property src_info {type:XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA8} [get_ports rx_ref_clk_p]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA7} [get_ports rx_ref_clk_n]
set_property src_info {type:XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE8} [get_ports {rx_data_p[0]}]
set_property src_info {type:XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE7} [get_ports {rx_data_n[0]}]
set_property src_info {type:XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH10} [get_ports {rx_data_p[1]}]
set_property src_info {type:XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH9} [get_ports {rx_data_n[1]}]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG8} [get_ports {rx_data_p[2]}]
set_property src_info {type:XDC file:3 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG7} [get_ports {rx_data_n[2]}]
set_property src_info {type:XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AJ8} [get_ports {rx_data_p[3]}]
set_property src_info {type:XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AJ7} [get_ports {rx_data_n[3]}]
set_property src_info {type:XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG21 IOSTANDARD LVDS_25} [get_ports rx_sync_p]
set_property src_info {type:XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH21 IOSTANDARD LVDS_25} [get_ports rx_sync_n]
set_property src_info {type:XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_sysref_p]
set_property src_info {type:XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AJ19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_sysref_n]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD10} [get_ports tx_ref_clk_p]
set_property src_info {type:XDC file:3 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD9} [get_ports tx_ref_clk_n]
set_property src_info {type:XDC file:3 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK2} [get_ports {tx_data_p[0]}]
set_property src_info {type:XDC file:3 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK1} [get_ports {tx_data_n[0]}]
set_property src_info {type:XDC file:3 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK10} [get_ports {tx_data_p[1]}]
set_property src_info {type:XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK9} [get_ports {tx_data_n[1]}]
set_property src_info {type:XDC file:3 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AJ4} [get_ports {tx_data_p[2]}]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AJ3} [get_ports {tx_data_n[2]}]
set_property src_info {type:XDC file:3 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK6} [get_ports {tx_data_p[3]}]
set_property src_info {type:XDC file:3 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK5} [get_ports {tx_data_n[3]}]
set_property src_info {type:XDC file:3 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports tx_sync_p]
set_property src_info {type:XDC file:3 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports tx_sync_n]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AJ20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports tx_sysref_p]
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AK20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports tx_sysref_n]
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH23 IOSTANDARD LVCMOS25} [get_ports spi_csn_clk]
set_property src_info {type:XDC file:3 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG24 IOSTANDARD LVCMOS25} [get_ports spi_csn_dac]
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE21 IOSTANDARD LVCMOS25} [get_ports spi_csn_adc]
set_property src_info {type:XDC file:3 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AH24 IOSTANDARD LVCMOS25} [get_ports spi_clk]
set_property src_info {type:XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD21 IOSTANDARD LVCMOS25} [get_ports spi_sdio]
set_property src_info {type:XDC file:3 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG19 IOSTANDARD LVCMOS25} [get_ports spi_dir]
set_property src_info {type:XDC file:3 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF19 IOSTANDARD LVCMOS25} [get_ports clkd_sync]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG25 IOSTANDARD LVCMOS25} [get_ports dac_reset]
set_property src_info {type:XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF24 IOSTANDARD LVCMOS25} [get_ports dac_txen]
set_property src_info {type:XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AG22 IOSTANDARD LVCMOS25} [get_ports adc_pd]
set_property src_info {type:XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA22 IOSTANDARD LVCMOS25} [get_ports {clkd_status[0]}]
set_property src_info {type:XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AA23 IOSTANDARD LVCMOS25} [get_ports {clkd_status[1]}]
set_property src_info {type:XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AF23 IOSTANDARD LVCMOS25} [get_ports dac_irq]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AD23 IOSTANDARD LVCMOS25} [get_ports adc_fda]
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AE23 IOSTANDARD LVCMOS25} [get_ports adc_fdb]
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AJ23 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports trig_p]
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AJ24 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports trig_n]
set_property src_info {type:XDC file:4 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN  H9  IOSTANDARD LVDS}     [get_ports sys_clk_p]
set_property src_info {type:XDC file:4 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN  G9  IOSTANDARD LVDS}     [get_ports sys_clk_n]
set_property src_info {type:XDC file:4 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN  A8  IOSTANDARD LVCMOS15} [get_ports sys_rst]
set_property src_info {type:XDC file:5 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  P28   IOSTANDARD LVCMOS25}           [get_ports hdmi_out_clk]
set_property src_info {type:XDC file:5 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U21   IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_vsync]
set_property src_info {type:XDC file:5 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  R22   IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_hsync]
set_property src_info {type:XDC file:5 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  V24   IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data_e]
set_property src_info {type:XDC file:5 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U24   IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[0]]
set_property src_info {type:XDC file:5 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  T22   IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[1]]
set_property src_info {type:XDC file:5 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  R23   IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[2]]
set_property src_info {type:XDC file:5 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AA25  IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[3]]
set_property src_info {type:XDC file:5 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AE28  IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[4]]
set_property src_info {type:XDC file:5 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  T23   IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[5]]
set_property src_info {type:XDC file:5 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AB25  IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[6]]
set_property src_info {type:XDC file:5 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  T27   IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[7]]
set_property src_info {type:XDC file:5 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AD26  IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[8]]
set_property src_info {type:XDC file:5 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AB26  IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[9]]
set_property src_info {type:XDC file:5 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AA28  IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[10]]
set_property src_info {type:XDC file:5 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AC26  IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[11]]
set_property src_info {type:XDC file:5 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AE30  IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[12]]
set_property src_info {type:XDC file:5 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  Y25   IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[13]]
set_property src_info {type:XDC file:5 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AA29  IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[14]]
set_property src_info {type:XDC file:5 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AD30  IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[15]]
set_property src_info {type:XDC file:5 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  Y28   IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[16]]
set_property src_info {type:XDC file:5 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AF28  IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[17]]
set_property src_info {type:XDC file:5 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  V22   IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[18]]
set_property src_info {type:XDC file:5 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AA27  IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[19]]
set_property src_info {type:XDC file:5 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  U22   IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[20]]
set_property src_info {type:XDC file:5 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  N28   IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[21]]
set_property src_info {type:XDC file:5 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  V21   IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[22]]
set_property src_info {type:XDC file:5 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AC22  IOSTANDARD LVCMOS25  IOB TRUE} [get_ports hdmi_data[23]]
set_property src_info {type:XDC file:5 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AC21  IOSTANDARD LVCMOS25} [get_ports spdif]
set_property src_info {type:XDC file:5 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AJ14  IOSTANDARD LVCMOS25 PULLTYPE PULLUP} [get_ports iic_scl]
set_property src_info {type:XDC file:5 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AJ18  IOSTANDARD LVCMOS25 PULLTYPE PULLUP} [get_ports iic_sda]
set_property src_info {type:XDC file:5 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AB17  IOSTANDARD LVCMOS25} [get_ports gpio_bd[0]]           ; ## GPIO_DIP_SW0
set_property src_info {type:XDC file:5 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AC16  IOSTANDARD LVCMOS25} [get_ports gpio_bd[1]]           ; ## GPIO_DIP_SW1
set_property src_info {type:XDC file:5 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AC17  IOSTANDARD LVCMOS25} [get_ports gpio_bd[2]]           ; ## GPIO_DIP_SW2
set_property src_info {type:XDC file:5 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AJ13  IOSTANDARD LVCMOS25} [get_ports gpio_bd[3]]           ; ## GPIO_DIP_SW3
set_property src_info {type:XDC file:5 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  AK25  IOSTANDARD LVCMOS25} [get_ports gpio_bd[4]]           ; ## GPIO_SW_LEFT
set_property src_info {type:XDC file:5 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  K15   IOSTANDARD LVCMOS15} [get_ports gpio_bd[5]]           ; ## GPIO_SW_CENTER
set_property src_info {type:XDC file:5 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  R27   IOSTANDARD LVCMOS25} [get_ports gpio_bd[6]]           ; ## GPIO_SW_RIGHT
set_property src_info {type:XDC file:5 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  Y21   IOSTANDARD LVCMOS25} [get_ports gpio_bd[7]]           ; ## GPIO_LED_LEFT
set_property src_info {type:XDC file:5 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  G2    IOSTANDARD LVCMOS15} [get_ports gpio_bd[8]]           ; ## GPIO_LED_CENTER
set_property src_info {type:XDC file:5 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  W21   IOSTANDARD LVCMOS25} [get_ports gpio_bd[9]]           ; ## GPIO_LED_RIGHT
set_property src_info {type:XDC file:5 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  A17   IOSTANDARD LVCMOS15} [get_ports gpio_bd[10]]          ; ## GPIO_LED_0
set_property src_info {type:XDC file:5 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  H14   IOSTANDARD LVCMOS15} [get_ports gpio_bd[11]]          ; ## XADC_GPIO_0
set_property src_info {type:XDC file:5 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  J15   IOSTANDARD LVCMOS15} [get_ports gpio_bd[12]]          ; ## XADC_GPIO_1
set_property src_info {type:XDC file:5 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  J16   IOSTANDARD LVCMOS15} [get_ports gpio_bd[13]]          ; ## XADC_GPIO_2
set_property src_info {type:XDC file:5 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property  -dict {PACKAGE_PIN  J14   IOSTANDARD LVCMOS15} [get_ports gpio_bd[14]]          ; ## XADC_GPIO_3
current_instance i_system_wrapper/system_i/axi_ad9144_jesd/tx_axi/inst
set_property src_info {type:SCOPED_XDC file:6 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_tx/i_cdc_status/cdc_hold_reg[*]/C}] -to [get_pins {i_up_tx/i_cdc_status/out_data_reg[*]/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9144_jesd/tx_axi/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:6 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_common/up_cfg_*_reg*/C}] -to [get_pins {i_up_common/core_cfg_*_reg*/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9144_jesd/tx_axi/inst/core_clk]]]
set_property src_info {type:SCOPED_XDC file:6 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_tx/up_cfg_ilas_data_*_reg*/C}] -to [get_cells {i_up_tx/*core_ilas_config_data_reg*}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9144_jesd/tx_axi/inst/core_clk]]]
set_property src_info {type:SCOPED_XDC file:6 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_tx/up_cfg_*_reg*/C}] -to [get_pins {i_up_common/core_extra_cfg_reg[*]/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9144_jesd/tx_axi/inst/core_clk]]]
set_property src_info {type:SCOPED_XDC file:6 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_sysref/up_cfg_*_reg*/C}] -to [get_pins {i_up_common/core_extra_cfg_reg[*]/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9144_jesd/tx_axi/inst/core_clk]]]
current_instance
current_instance i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst
set_property src_info {type:SCOPED_XDC file:7 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_rx/i_cdc_status/cdc_hold_reg[*]/C}] -to [get_pins {i_up_rx/i_cdc_status/out_data_reg[*]/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_rx/i_cdc_cfg/cdc_hold_reg[*]/C}] -to [get_pins {i_up_rx/i_cdc_cfg/out_data_reg[*]/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/core_clk]]]
set_property src_info {type:SCOPED_XDC file:7 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/core_clk]] -to [get_pins {i_up_rx/*i_up_rx_lane/up_status_latency_reg[*]/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_rx/gen_lane[*].i_up_rx_lane/i_ilas_mem/mem_reg_*/*/CLK}] -to [get_pins {i_up_rx/gen_lane[*].i_up_rx_lane/i_ilas_mem/up_rdata_reg[*]/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/s_axi_aclk]]]
set_property src_info {type:SCOPED_XDC file:7 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_common/up_cfg_*_reg*/C}] -to [get_pins {i_up_common/core_cfg_*_reg*/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/core_clk]]]
set_property src_info {type:SCOPED_XDC file:7 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_rx/up_cfg_*_reg*/C}] -to [get_pins {i_up_common/core_extra_cfg_reg[*]/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/core_clk]]]
set_property src_info {type:SCOPED_XDC file:7 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins {i_up_sysref/up_cfg_*_reg*/C}] -to [get_pins {i_up_common/core_extra_cfg_reg[*]/D}] [get_property -min PERIOD [get_clocks -of_objects [get_pins i_system_wrapper/system_i/axi_ad9680_jesd/rx_axi/inst/core_clk]]]
