trigger:
- master
- dev/*

pr:
- master

variables:
- group: noos_releases_group_variables
- name: isMaster
  value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

jobs:
- job: Projects
  pool: LocalPool
  steps:
  - checkout: self
    fetchDepth: 50
    submodules: true
    clean: true
    persistCredentials: true
  - script: 'python3 ./tools/scripts/build_projects.py . 
               -export_dir $(RELEASE_DIR)
               -log_dir $(LOG_DIR)
               -builds_dir $(BUILDS_DIR)'
    displayName: 'Run project build'
  - task: PublishPipelineArtifact@1
    condition: eq(variables.isMaster, true)
    inputs:
      targetPath: '$(Build.Repository.LocalPath)/$(RELEASE_DIR)'
      artifact: '$(ARTIFACT_NAME)'
      publishLocation: 'pipeline'
  - task: PublishPipelineArtifact@1
    condition: true
    inputs:
      targetPath: '$(Build.Repository.LocalPath)/$(LOG_DIR)'
      artifact: 'logs_$(System.JobId)'
      publishLocation: 'pipeline'
